AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
