services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-pw
      - POSTGRES_DB=testdb
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
