version: "3.3"
services:
  db:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - '${DEV_DB_PORT}:5432'
    volumes:
      - ./public/postgres-data # persist data even if container shuts down
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rake spec"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
