# docker-compose.yml
version: '3'
services:
  db_test:
    image: "postgres" # use latest official postgres version
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - '${TEST_DB_PORT}:5432'
    volumes:
      - ./public/postgres-data-test:/var/lib/postgresql/data # persist data even if container shuts down
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rake spec"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db_test
