source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.5"

gem 'rspec-rails'
gem 'factory_bot_rails'
gem "rails", "~> 7.0.4", ">= 7.0.4.3"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

gem 'faraday'
gem 'faraday_middleware'

gem 'rack-cors'

gem "devise"

gem 'dotenv-rails', groups: [:development, :test]
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false

gem 'googleauth'

group :development do
  gem "web-console"
end
