version: "3.7"
services:
  compiler:
    build: .
    volumes:
      - .:/src
    command: >
      sh -c   "mkdir -p Web/bin &&
              cd Web &&
              ls -la && cd bin && emcmake cmake .. &&
              mkdir res && mkdir res/shaders && cp -p ../embed/shaders/* res/shaders &&
              cmake --build ."
