version: '3'

services:
  unit-test:
    build:
      context: .
      dockerfile: ./docker/desktop.Dockerfile
    volumes:
      - .:/src
    working_dir: /src
    command: >
        bash -c "cmake . && cmake --build ."
  compile-emscripten:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    volumes:
      - .:/src
    command: >
      sh -c   "cd Web &&
              emcmake cmake . &&
              cmake --build ."
volumes:
  myapp:
